window.translations_en = {
  "app_title": "Guitar Chord and Note Detector",
  "main_title": "Guitar Analyzer",
  "subtitle": "Play a guitar note or chord. The system will try to guess the note, string/fret, and if possible, the chord.",
  "status_stopped": "Stopped",
  "status_listening": "Listening",
  "btn_start": "Start Listening",
  "btn_stop": "Stop Listening",
  "label_chord_detected": "Detected Chord",
  "msg_play_chord": "Play multiple strings to try to detect a chord.",
  "label_main_note": "Main Note",
  "label_string_fret": "Suggested String / Fret",
  "hint_text": "Tip: use a <strong>well-tuned guitar</strong>, play cleanly near the mic, and avoid background noise. Chord detection is approximate (not as precise as a dedicated plugin).",
  "msg_no_clear_note": "No clear note detected.",
  "msg_deviation": "Hz · deviation",
  "msg_cents": "cents",
  "msg_approx": "(approx)",
  "msg_suggested_note": "Note at suggested position:",
  "msg_detected_notes": "detected notes:",
  "err_no_audiocontext": "Your browser does not support AudioContext.",
  "err_mic_access": "Could not access microphone:",
  "label_language": "Language:",
  "label_notation": "Notation:",
  "notation_latin": "Latin (Do, Re...)",
  "notation_anglo": "Anglo (C, D...)",
  "label_interval": "Update (ms):",
  "btn_save_interval": "✓",
  "msg_interval_saved": "Interval configuration saved.",
  "chord_major": "Major",
  "chord_minor": "Minor",
  "chord_dom7": "Dominant 7",
  "chord_maj7": "Major 7",
  "chord_m7": "Minor 7",
  "chord_dim": "Diminished",
  "chord_aug": "Augmented",
  "chord_sus2": "Sus2",
  "chord_sus4": "Sus4"
};
