window.translations_es = {
  tool_visual_tab_title: "Reproductor Visual de Tabs",
  tool_visual_tab_desc:
    "Visualiza tus tablaturas favoritas de una forma nueva.",
  loading: "Cargando tablaturas...",
  back_to_list: "Volver a la lista",
  legend_note: "Nota",
  legend_chord: "Acorde",
  select_artist: "Seleccionar Artista",
  unknown_artist: "Artista Desconocido",
  unknown_song: "Cancion Desconocida",
  show_chords: "Mostrar Acordes",
  label_sound_profile: "Sonido:",
  sound_clean: "Guitarra limpia",
  sound_jazz: "Guitarra jazz",
  sound_dist1: "Distorsion 1",
  sound_dist2: "Distorsion 2",
  label_arrangement: "Arreglo:",
  play_tab: "Reproducir",
  pause_tab: "Pausar",
  stop_tab: "Detener",
  transport_jump_start: "Ir al inicio",
  transport_prev_measure: "Compas anterior",
  transport_next_measure: "Compas siguiente",
  transport_jump_end: "Ir al final",
};
