window.translations_en = {
  tool_visual_tab_title: "Visual Tab Player",
  tool_visual_tab_desc: "Visualize your favorite tabs in a new way.",
  loading: "Loading tabs...",
  back_to_list: "Back to List",
  legend_note: "Note",
  legend_chord: "Chord",
  select_artist: "Select Artist",
  unknown_artist: "Unknown Artist",
  unknown_song: "Unknown Song",
  show_chords: "Show Chords",
  label_sound_profile: "Sound:",
  sound_clean: "Clean Guitar",
  sound_jazz: "Jazz Guitar",
  sound_dist1: "Distortion 1",
  sound_dist2: "Distortion 2",
  label_arrangement: "Arrangement:",
  play_tab: "Play",
  pause_tab: "Pause",
  stop_tab: "Stop",
  transport_jump_start: "Go to Start",
  transport_prev_measure: "Previous Measure",
  transport_next_measure: "Next Measure",
  transport_jump_end: "Go to End",
};
