window.translations_es = {
  "app_title": "Detector de acordes y notas de guitarra",
  "main_title": "Analizador de Guitarra",
  "subtitle": "Toca una nota o un acorde de guitarra. El sistema intentará adivinar la nota, la cuerda/traste y, si es posible, el acorde.",
  "status_stopped": "Parado",
  "status_listening": "Escuchando",
  "btn_start": "Empezar a escuchar",
  "btn_stop": "Parar escucha",
  "label_chord_detected": "Acorde detectado",
  "msg_play_chord": "Toca varias cuerdas para intentar detectar un acorde.",
  "label_main_note": "Nota principal",
  "label_string_fret": "Cuerda / traste sugeridos",
  "hint_text": "Consejo: usa una <strong>guitarra bien afinada</strong>, toca limpio cerca del micro y evita ruido de fondo. La detección de acordes es aproximada (no es tan precisa como un plugin dedicado).",
  "msg_no_clear_note": "No se detecta una nota clara.",
  "msg_deviation": "Hz · desviación",
  "msg_cents": "cents",
  "msg_approx": "(aprox)",
  "msg_suggested_note": "Nota de la posición sugerida:",
  "msg_detected_notes": "notas detectadas:",
  "err_no_audiocontext": "Tu navegador no soporta AudioContext.",
  "err_mic_access": "No se pudo acceder al micrófono:",
  "label_language": "Idioma:",
  "chord_major": "Mayor",
  "chord_minor": "Menor",
  "chord_dom7": "Dominante 7",
  "chord_maj7": "Mayor 7",
  "chord_m7": "Menor 7",
  "chord_dim": "Disminuido",
  "chord_aug": "Aumentado",
  "chord_sus2": "Sus2",
  "chord_sus4": "Sus4"
};
